from exceptions.BaseException import BaseException

class AuthException(BaseException):
    pass